### ISSUE TITLE
BIOS Settings

### ISSUE THREAD

**Issue by gabrierf** [rodrigomatta/EFI-X99-MACHINIST-RS9-RX6600#1]
### **_Suggestions from BIOS Config_**
what's enabled and what's not

Turbo Boost Unlock: Yes / No

**Disable**
Fast Boot
Secure Boot
Serial/COM Port
Parallel Port
VT-d (can be enabled if you set `DisableIoMapper` to YES)
Compatibility Support Module (CSM).
Thunderbolt(For initial install, as Thunderbolt can cause issues if not setup correctly)
Intel SGX
Intel Platform Trust
CFG Lock (MSR 0xE2 write protection)
This must be off, if you can't find the option then `ENABLE` `AppleXcpmCfgLock`.
Your hack will not boot with CFG-Lock enabled.
For 10.10 and older, you'll need to ENABLE `AppleCpuPmCfgLock` as well.

**Enable**
VT-x
Above 4G decoding.
This must be on, if you can't find the option then add `npci=0x2000` to `boot-args`.
Do not have both this option and npci on boot-args enabled at the same time.
Hyper-Threading
Execute Disable Bit
EHCI/XHCI Hand-off
OS type: Windows 8.1/10/11 UEFI Mode
SATA Mode: AHCI

**_Suggestions to better work on the boards. Your Config is crashing on my card_**

**Comment by rodrigomatta** [comment]
Thank you, your recommendations were added to the project's README.md
